### ISSUE TITLE
mistlands_worldgen changes terrain, even in a fresh world - missing dungeons

### ISSUE THREAD

**Issue by madsvcarlsen** [JereKuusela/valheim-upgrade_world#29]
To reproduce:

Generate a new world with seed `BJ8bLM85cI`.

`goto -1403,7614`

Find a dungeon there.

Run `upgrade mistlands_worldgen`

The dungeon is now gone - covered by a mountain. Logging shows the dungeon is still nearby - but probably below the terrain.

**Comment by JereKuusela** [comment]
I'm not seeing any issue.

Redistributing locations doesn't guarantee the same placement for already explored worlds. In this case the dungeon was moved somewhere else.

**Comment by Kurisu86** [comment]
Same issue here. In my case, the Infested mine was within range of mod recognized player structures. In that case, would it relocate the dungeon, or simply not generate it at all? 

Aside from ground generation changes at the base (a few structure pieces broke due to the ground being gone, walking out the door now requires a feather cape or high health foods, and the basement is gone and everything down there broke and the resources ended up scattered on the floor of the level above), everything else is beautifully reset in the explored biome and where it is expected to be.

I have a back-up of the world from before using the mod, but players on my server as satisfied with the overall result and we will not be restoring the back-up.
